### register user

POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "userName":"someName",
    "email":"somemail@mail.com",
    "password":"somePassword"
}

### bad request upon register user/missing some fields

POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email":"somemail@mail.com",
    "password":"somePassword"
}

### bad request upon register user/email in use

POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "userName":"someName",
    "email":"stepan_bandera@gmail.com",
    "password":"somePassword"
}

### log in user

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"somemail@mail.com",
    "password":"somePassword"
}

### log in user error/wrong data

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"stepan_bandera@gmail.com",
    "password":"somePassword"
}

### logout user
POST http://localhost:5000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNvbWVtYWlsQG1haWwuY29tIiwiaWQiOiI2NTdjNmQzZTRlZGI0Y2YzYjdmNWE3NGIiLCJpYXQiOjE3MDI2NTMyNDYsImV4cCI6MTcwMjczOTY0Nn0.g7Dkfn0yn0fpE1MKCN2Sl1c3_4AEJAKKIQEGUzf4cXg

### get current user
GET http://localhost:5000/auth/current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNvbWVtYWlsQG1haWwuY29tIiwiaWQiOiI2NTdjNmQzZTRlZGI0Y2YzYjdmNWE3NGIiLCJpYXQiOjE3MDI2NTMyNDYsImV4cCI6MTcwMjczOTY0Nn0.g7Dkfn0yn0fpE1MKCN2Sl1c3_4AEJAKKIQEGUzf4cXg

